name: Copy file on Wedos FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy snake on FTP
    runs-on: ubuntu-latest
    steps:

    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        dry-run: true